openapi: 3.0.0
info:
  title: B137 API
  description: API documentation for resolving DID names using the B137 protocol.
  version: 1.0.0
servers:
  - url: https://www.b137.io/openapi/v1
paths:

  /resolveName:
    get:
      summary: Resolve DID Name
      description: Retrieve the address corresponding to the requested DID name. This value will be consistent with the latest block height a short time after the block has been confirmed.
      parameters:
        - name: did
          in: query
          required: true
          schema:
            type: string
          description: The DID name to resolve.
          example: gene
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: '0: Success, -1: Error'
                    example: 0
                  data:
                    type: object
                    properties:
                      address:
                        type: string
                        nullable: true
                        description: The Bitcoin address corresponding to the requested DID name.
                        example: "bc1plhw3qceajqpv2q96zt365z278ce5jyecz0d5zjrnrad96y7c34msk4v7u6"

  /resolveAddress:
    get:
      summary: Resolve wallet address
      description: Retrieve all DIDs corresponding to the requested wallet address. This value will be consistent with the latest block height a short time after the block has been confirmed.
      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
          description: The wallet address to resolve.
          example: "bc1plhw3qceajqpv2q96zt365z278ce5jyecz0d5zjrnrad96y7c34msk4v7u6"
        - name: start
          in: query
          required: true
          schema:
            type: integer
            default: 0
          description: The starting index for the paginated results.
          example: 0
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            default: 10
          description: The number of items to retrieve per page.
          example: 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: '0: Success, -1: Error'
                    example: 0
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        items:
                          type: string
                          description: A DID name owned by the requested Bitcoin address.
                          example: "gene"
                        description: A list of DID names owned by the requested Bitcoin address.
                        example: ["did1", "did2", "gene"]
                      total:
                        type: integer
                        description: The total number of DID names owned by the requested Bitcoin address.
                        example: 3
        
  /getDidDetail:
    get:
      summary: Check inscription info of a DID.
      description: Retrieve and return all on-chain inscription information for a specific DID name.
      parameters:
        - name: did
          in: query
          required: true
          schema:
            type: string
          description: The DID name to query.
          example: gene
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: '0: Success, -1: Error'
                    example: 0
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        owner:
                          type: string
                          description: The owner of the DID.
                          example: "bc1plhw3qceajqpv2q96zt365z278ce5jyecz0d5zjrnrad96y7c34msk4v7u6"
                        inscriptionId:
                          type: string
                          description: The inscription ID of the DID.
                          example: "c562cbbc69346b355771342047967a58be2eed054cfb2961478035b277af5b4ci0"
                        genesisBlock:
                          type: number
                          description: The genesis block of the DID.
                          example: 841023
                    description: A list of on-chain inscription information for the specified DID.
                    example: [
                      {
                        "owner": "bc1plhw3qceajqpv2q96zt365z278ce5jyecz0d5zjrnrad96y7c34msk4v7u6",
                        "inscriptionId": "c562cbbc69346b355771342047967a58be2eed054cfb2961478035b277af5b4ci0",
                        "genesisBlock": 841023
                      }
                    ]

  /getTldDetail:
    get:
      summary: Check inscription info of a TLD.
      description: Retrieve and return all on-chain inscription information for a specific TLD name.
      parameters:
        - name: did
          in: query
          required: true
          schema:
            type: string
          description: The tld name to query.
          example: b137
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: '0: Success, -1: Error'
                    example: 0
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        owner:
                          type: string
                          description: The owner of the TLD.
                          example: "bc1ps96500phcr0y83ysfsfe2qt25few7rp6k5thn8kcmt9ap4zfa8pqu6aqkt"
                        inscriptionId:
                          type: string
                          description: The inscription ID of the TLD.
                          example: "2e4cd8f6a235300a4d9d4d1a292d8c9c4ee87388a9b4d96d6a6ca870a1151955i0"
                        genesisBlock:
                          type: number
                          description: The genesis block of the TLD.
                          example: 840359
                    description: A list of on-chain inscription information for the specified TLD.
                    example: [
                      {
                        "owner": "bc1ps96500phcr0y83ysfsfe2qt25few7rp6k5thn8kcmt9ap4zfa8pqu6aqkt",
                        "inscriptionId": "2e4cd8f6a235300a4d9d4d1a292d8c9c4ee87388a9b4d96d6a6ca870a1151955i0",
                        "genesisBlock": 840359
                      }
                    ]

  /getPrimary:
    get:
      summary: Get Primary DID of a Bitcoin address, which is setted on B137 Profile page.
      description: Retrieve the primary DIDs corresponding to the requested wallet address.
      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
          description: The wallet address to resolve.
          example: "bc1plhw3qceajqpv2q96zt365z278ce5jyecz0d5zjrnrad96y7c34msk4v7u6"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: '0: Success, -1: Error'
                    example: 0
                  data:
                    type: string
                    nullable: true
                    description: The primary DID name.
                    example: "gene"

  /getBindedTLD:
    get:
      summary: Get Binded TLDs
      description: Retrieve all communities a DID has joined (binded top-level domains). This data will be consistent with the latest block height a short time after the block has been confirmed.
      parameters:
        - name: did
          in: query
          required: true
          schema:
            type: string
          description: The DID name to query.
          example: revo
        - name: start
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: The starting index for the paginated results.
          example: 0
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: The number of items to retrieve per page.
          example: 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    description: '0: Success, -1: Error'
                    example: 0
                  data:
                    type: object
                    properties:
                      list:
                       
